In [1]:
import numpy as np

In [2]:
x = np.array([2,8,-4])

In [3]:
y = np.array([1,-7,3])

In [4]:
np.dot(x,y)

-66

In [5]:
np.dot(y,x) # vector . vector

-66

In [7]:
z = np.array([[5],[4],[3]])

In [34]:
z

array([[5],
       [4],
       [3]])

In [36]:
x

array([ 2,  8, -4])

In [37]:
y

array([ 1, -7,  3])

In [8]:
np.dot(x,z)

array([30])

In [44]:
np.dot(z,x)

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [10]:
z.shape

(3, 1)

In [45]:
x.shape

(3,)

In [46]:
y.shape

(3,)

In [48]:
z.shape

(3, 1)

In [55]:
x_reshaped = x.reshape(3,1)
x_reshaped # x_reshaped -> (3x1)

array([[ 2],
       [ 8],
       [-4]])

In [56]:
x_reshaped.shape

(3, 1)

In [57]:
x.shape 

(3,)

In [58]:
np.dot(z,x_reshaped)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [60]:
np.dot(x_reshaped,z)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [61]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[ 2,  8, -4]])

In [62]:
x_reshaped.shape # 1x3

(1, 3)

In [64]:
z.shape # 3x1

(3, 1)

In [67]:
x_reshaped

array([[ 2,  8, -4]])

In [68]:
z

array([[5],
       [4],
       [3]])

In [65]:
np.dot(z,x_reshaped) # 3x1 . 1x3 -> 3x3

array([[ 10,  40, -20],
       [  8,  32, -16],
       [  6,  24, -12]])

In [66]:
np.dot(x_reshaped,z)

array([[30]])

In [39]:
np.dot(3,5)

15

In [40]:
np.dot(5,3)

15

In [41]:
5*x # Scalar . Vector

array([ 10,  40, -20])

In [42]:
10*z

array([[50],
       [40],
       [30]])

In [43]:
-2*y

array([-2, 14, -6])