In [1]:
import numpy as np
#for addition and subtraction, dimensions of matrices should be exactly the same
# 2x3, 2x3
# 2x3 , 3x2 -> cannot be

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])

In [4]:
m1 + m2 #adding the indexes one by one

array([[14, 20, 13],
       [-2,  3,  9]])

In [8]:
m2 + m1
#m2 + m1 = m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [6]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [9]:
m2 -m1
# m2 - m1 != m1 - m2

array([[  4,  -4,   1],
       [  4,   3, -19]])

In [12]:
v1 = np.array([1,2,3,4,5])

In [13]:
v2 = np.array([5,4,3,2,1])

In [14]:
v1 + v2

array([6, 6, 6, 6, 6])

In [15]:
v1 -v2 

array([-4, -2,  0,  2,  4])

In [16]:
v2 - v1

array([ 4,  2,  0, -2, -4])

In [18]:
# you cannot add or subtract 2x3 3x2 matrices
# you cannot add or subtract 5x1 1x5 vectors
# but you can add to matrices/vectors a scalar
v1 + 2 # add to every element +2

array([3, 4, 5, 6, 7])

In [20]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [21]:
m1 + 5 # add every element +5

array([[10, 17, 11],
       [ 2,  5, 19]])