In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [7]:
data = pd.read_csv('../Part_5_ML/S34_L219/multiple_linear_regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [9]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [12]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler() 
#scaler contains the standardizing information

In [18]:
scaler.fit(x)
#scaler now contains the mean and stdev information of x
#scaling mechanism is ready

StandardScaler()

In [22]:
x_scaled = scaler.transform(x)
#to start the mechanism use transform to turn x's parameters into standard form
#x_scaled is now Xs parameters but in scaled form

In [24]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [26]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [29]:
reg.intercept_

3.330238095238095

In [35]:
reg_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Feature'])
reg_summary['Weight'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [37]:
reg_summary
#bigger the Weights bigger the impact
#we standardized the values so that we can easly observer which value has bigger impact
#if a value has too little weight, then we can ignore

Feature    Weight
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [39]:
#prediction with standardized coefficients
#the output should be transformed too
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [41]:
reg.predict(new_data)

C:\Users\emirp\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [43]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [45]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [46]:
#what if we remove 'Random 1,2,3' variable
#conclusion: if the impact is too low it's not important if we leave it or delete it

In [50]:
reg_simple = LinearRegression()  #create linear regression object
x_simple_matrix = x_scaled[:,0].reshape(-1,1) #create a x_simple matrix that contains just SAT scores and full of 0s
# [84,2]
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [51]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1)) #predict for every row the GPA
#there is no significant difference between the out[45] and out[51]

array([3.08970998, 3.25527879])