In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [6]:
data = pd.read_csv('../Part_5_ML/S34_L212/multiple_linear_regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [8]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [9]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [11]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [13]:
reg.coef_
#slope of inputs

array([ 0.00165354, -0.00826982])

In [15]:
reg.intercept_
#constant

0.29603261264909264

In [17]:
reg.score(x,y)
#R-square

0.40668119528142843

In [24]:
#adj r-square calculating
r2 = reg.score(x,y)
n = x.shape[0] # take the 84
p = x.shape[1] # take the 2
adj_r2 = 1-(1-r2)*(n-1)/(n-p-1) #adj. r-square formula
adj_r2

0.39203134825134023

In [25]:
#adj. r-square function
def adj_r_square(x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adj_r2
adj_r_square(x,y)

0.39203134825134023

In [27]:
from sklearn.feature_selection import f_regression

In [29]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [35]:
p_values = f_regression(x,y)[1]
p_values_round = p_values.round(3)
p_values_round
#throw the second input cause its bigger than 0.05

array([0.   , 0.676])

In [42]:
reg_summary = pd.DataFrame(data= x.columns.values, columns = ['Features'])
reg_summary
#data = ['...'] rather than that use x.columns.values function

Features
0         SAT
1  Rand 1,2,3

In [41]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values_round
reg_summary
#p-values best ways to determine if a variables is redundant(useless)
#but provide no info about how useful a variable is
#it's NOT the case if two variable has p-value with 0.000 but they have equal priority/importance

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676