In [1]:
import numpy as np

In [2]:
A = np.array([[5,12,6],[-3,0,14]])

In [3]:
A.T # .T to transpose

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
s = np.array([5])

In [5]:
s.T # 1x1 transpose -> 1x1

array([5])

In [8]:
v1 = np.array([1,2,3])
v1

array([1, 2, 3])

In [7]:
v1.T
#That's because, in Phyton 1D arrays couldn't transposed

array([1, 2, 3])

In [11]:
v1.shape

(3,)

In [21]:
v1_reshaped = v1.reshape(1,3)
v1_reshaped

array([[1, 2, 3]])

In [22]:
v1_reshaped.shape

(1, 3)

In [23]:
v1_reshaped.T
#That's allowed

array([[1],
       [2],
       [3]])

In [26]:
v1_reshaped2 = v1_reshaped.reshape(3,1)
v1_reshaped2

array([[1],
       [2],
       [3]])

In [27]:
v1_reshaped2.shape

(3, 1)

In [28]:
v1_reshaped2.T

array([[1, 2, 3]])