In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [70]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [71]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [72]:
train_test_split(a)
#get difference splitted arrays every time

[array([ 42,  83,  75,  39,  17,  41,  97,  21,  58,  28,  66,  73,  31,
         62,  35,  91,  80,  96,  99,  37, 100,  76,  79,   9,  11,  92,
         71,  10,  24,  89,  49,  70,  95,  54,  43,  44,  18,  82,  64,
          3,  53,  93,   4,  57,  48,  33,   1,   7,  46,  94,  56,  14,
         85,  47,  15,  13,  32,  27,  74,  30,  52,  78,  50,  26,  19,
         87,  40,  98,  12,  86,  59,  69,  34,  23,  68]),
 array([29, 61, 25, 84, 55, 36, 67, 81, 88,  6, 22, 45,  2, 51, 60, 77, 65,
        72, 63,  8, 20, 38, 90,  5, 16])]

In [74]:
a_train, a_test = train_test_split(a)

In [75]:
a_train

array([50, 30,  9, 19, 42, 76, 92, 11, 10, 90, 57, 22, 24, 69, 67, 55,  6,
       47, 28, 40, 32, 39, 87, 27, 29, 64,  2, 82, 33, 25, 38, 86, 16, 66,
       62, 77, 44, 85, 13, 21, 93, 71,  8, 52, 45, 36, 18,  5, 49, 97, 17,
       80, 12, 51, 84, 41,  4, 99, 54, 37, 72, 68, 98, 35, 59, 83, 70, 60,
       15, 20, 63, 23, 75, 53, 79])

In [76]:
a_test

array([ 89,  94,  43,  88,  48, 100,   3,  56,  91,   1,  26,  96,   7,
        74,  95,  78,  65,  14,  31,  73,  61,  58,  81,  46,  34])

In [77]:
a_train, a_test = train_test_split(a, test_size=0.2)
#you can change the split size

In [78]:
a_train

array([ 81,  65,   5,  59,  93,  35,  97,  88,  50,  23,  95,  80,  28,
        18,  11,   1,  99,  29,  24,  74,  56,  85,  34,   8,  71,  96,
        19,  42,  37,  66,  69,  36,  52,  12,  26,  10,  45,  86,  21,
        72,  63,  55,  62,  46,  49,   2,  70,  22,  77,  47,  44,  16,
        64,  68, 100,  67,  43,  40,   7,  14,  33,  94,  58,  27,  32,
        61,  82,  57,  38,  73,  54,  31,  48,  30,   6,  51,  84,  20,
        75,  17])

In [79]:
a_test

array([87, 92,  4, 98,  3, 91, 15, 25, 78, 83, 76, 89, 90, 53,  9, 60, 13,
       79, 39, 41])

In [80]:
a_train, a_test = train_test_split(a, test_size=0.2, shuffle=False)
#you can close the shuffle option
#this removes day of the week effect, time dependencies, ...

In [81]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [82]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [83]:
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)
#random state is define the shuffle organization
#it gives us the chance every time we shuffle we get exactly the same arrays

In [84]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [85]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [86]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)
#we can use train_test_split for multiple arrays
#a_train has matched with b_train
#a_test has matched with b_test
#whatever happens to a_train happens exactly the same thing in b_train too

In [88]:
a_train 

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [90]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [92]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [93]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])