In [13]:
import numpy as np

In [14]:
numeric_data_1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
numeric_data_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [15]:
numeric_data_2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
numeric_data_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [16]:
numeric_data_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
numeric_data_NAN

ValueError: could not convert string '' to float64 at row 11, column 4.

In [17]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
numeric_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [18]:
import pandas as pd
numeric_data = pd.read_csv("Lending-Company-Numeric-Data-NAN.csv")
numeric_data

2000;40;365;3121;4241;13621
0     2000;40;365;3061;4171;15041
1     1000;40;365;2160;3280;15340
2     2000;40;365;3041;4241;15321
3     2000;50;365;3470;4820;13720
4     2000;40;365;3201;4141;14141
...                           ...
1037      2000;40;365;3401;;16600
1038      2000;40;365;;5440;16600
1039      ;40;365;4201;5001;16600
1040  1000;40;365;2080;3320;15600
1041  2000;40;365;4601;4601;16600

[1042 rows x 1 columns]

In [20]:
#solution = save them as string not numbers
numeric_data_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", dtype=str)
numeric_data_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [21]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
numeric_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [22]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                  delimiter=";",
                                  skip_header=2)
numeric_data_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [23]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                  delimiter=";",
                                  skip_header=2,
                                  skip_footer=2)
numeric_data_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [24]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                  delimiter=";",
                                  usecols = (0, 1, 5))
numeric_data_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [25]:
numeric_data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                  delimiter=";",
                                  usecols = (5, 1, 0))
#sorting the columns
numeric_data_NAN

array([[13621.,    40.,  2000.],
       [15041.,    40.,  2000.],
       [15340.,    40.,  1000.],
       ...,
       [16600.,    40.,    nan],
       [15600.,    40.,  1000.],
       [16600.,    40.,  2000.]])

In [28]:
numeric_data_NAN_5, numeric_data_NAN_1, numeric_data_NAN_0 = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                  delimiter=";",
                                  usecols = (5, 1, 0), unpack=True)
#sorting the columns
print(numeric_data_NAN_5)
print(numeric_data_NAN_1)
print(numeric_data_NAN_0)

[13621. 15041. 15340. ... 16600. 15600. 16600.]
[40. 40. 40. ... 40. 40. 40.]
[2000. 2000. 1000. ...   nan 1000. 2000.]
